import { SupportedToken } from '../types';
import { getChainConfig } from './chains';

export interface SupportedAsset {
  id: string; // Unique identifier e.g. "USDC-137", "USDT-1", "ETH-8453"
  symbol: SupportedToken;
  name: string;
  network: string;
  chainId: number;
  contractAddress: string; // Verified contract address or empty for native assets
  decimals: number;
  nativeGasToken: string; // 'POL' | 'ETH' | 'BNB' | 'AVAX' | 'SOL' | 'BTC'
  enabled: boolean;
  isNative?: boolean;
  rateToUSD: number;
  icon: string;
  color: string;
  description?: string;
}

/**
 * IRISME Multi-Chain Supported Assets Registry.
 * Verified real mainnet contracts and parameters.
 */
export const SUPPORTED_ASSETS: SupportedAsset[] = [
  // 1. POLYGON MAINNET (Chain ID: 137)
  {
    id: 'VERSE-137',
    symbol: 'VERSE',
    name: 'Verse (Polygon)',
    network: 'Polygon',
    chainId: 137,
    contractAddress: import.meta.env.VITE_VERSE_TOKEN_POLYGON || '0xc708d6f2153933daa50b2d0758955be0a93a8fec',
    decimals: 18,
    nativeGasToken: 'POL',
    enabled: true,
    rateToUSD: 0.0000176,
    icon: '⚡',
    color: '#00D2FE',
    description: 'Bitcoin.com Verse DEX & Rewards Token on Polygon',
  },
  {
    id: 'USDC-137',
    symbol: 'USDC',
    name: 'USD Coin (Polygon)',
    network: 'Polygon',
    chainId: 137,
    contractAddress: '0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359',
    decimals: 6,
    nativeGasToken: 'POL',
    enabled: true,
    rateToUSD: 1.0,
    icon: '$',
    color: '#3B82F6',
    description: 'Circle Native USDC on Polygon PoS',
  },
  {
    id: 'USDT-137',
    symbol: 'USDT',
    name: 'Tether USD (Polygon)',
    network: 'Polygon',
    chainId: 137,
    contractAddress: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F',
    decimals: 6,
    nativeGasToken: 'POL',
    enabled: true,
    rateToUSD: 1.0,
    icon: '₮',
    color: '#10B981',
    description: 'Tether USD on Polygon PoS',
  },
  {
    id: 'POL-137',
    symbol: 'POL',
    name: 'Polygon Token (POL)',
    network: 'Polygon',
    chainId: 137,
    contractAddress: '',
    decimals: 18,
    nativeGasToken: 'POL',
    enabled: true,
    isNative: true,
    rateToUSD: 0.44,
    icon: '🟣',
    color: '#8247E5',
    description: 'Native gas currency for Polygon PoS',
  },
  {
    id: 'MATIC-137',
    symbol: 'MATIC',
    name: 'Polygon Ecosystem Token (POL)',
    network: 'Polygon',
    chainId: 137,
    contractAddress: '',
    decimals: 18,
    nativeGasToken: 'POL',
    enabled: true,
    isNative: true,
    rateToUSD: 0.44,
    icon: '🟣',
    color: '#8247E5',
    description: 'Native gas currency for Polygon PoS',
  },
  {
    id: 'ETH-137',
    symbol: 'ETH',
    name: 'Wrapped Ether (Polygon)',
    network: 'Polygon',
    chainId: 137,
    contractAddress: '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619',
    decimals: 18,
    nativeGasToken: 'POL',
    enabled: true,
    rateToUSD: 2850.0,
    icon: 'Ξ',
    color: '#8B5CF6',
    description: 'WETH on Polygon',
  },
  {
    id: 'WBTC-137',
    symbol: 'WBTC',
    name: 'Wrapped Bitcoin (Polygon)',
    network: 'Polygon',
    chainId: 137,
    contractAddress: '0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6',
    decimals: 8,
    nativeGasToken: 'POL',
    enabled: true,
    rateToUSD: 96450.0,
    icon: '₿',
    color: '#F7931A',
    description: 'Wrapped BTC on Polygon PoS',
  },
  {
    id: 'DAI-137',
    symbol: 'DAI',
    name: 'Dai Stablecoin (Polygon)',
    network: 'Polygon',
    chainId: 137,
    contractAddress: '0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063',
    decimals: 18,
    nativeGasToken: 'POL',
    enabled: true,
    rateToUSD: 1.0,
    icon: '◈',
    color: '#F59E0B',
    description: 'MakerDAO Dai on Polygon',
  },

  // 2. ETHEREUM MAINNET (Chain ID: 1)
  {
    id: 'USDT-1',
    symbol: 'USDT',
    name: 'Tether USD (Ethereum)',
    network: 'Ethereum',
    chainId: 1,
    contractAddress: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
    decimals: 6,
    nativeGasToken: 'ETH',
    enabled: true,
    rateToUSD: 1.0,
    icon: '₮',
    color: '#10B981',
    description: 'Official Tether USDT ERC-20',
  },
  {
    id: 'USDC-1',
    symbol: 'USDC',
    name: 'USD Coin (Ethereum)',
    network: 'Ethereum',
    chainId: 1,
    contractAddress: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
    decimals: 6,
    nativeGasToken: 'ETH',
    enabled: true,
    rateToUSD: 1.0,
    icon: '$',
    color: '#3B82F6',
    description: 'Circle USDC ERC-20 on Ethereum',
  },
  {
    id: 'ETH-1',
    symbol: 'ETH',
    name: 'Ethereum (Native)',
    network: 'Ethereum',
    chainId: 1,
    contractAddress: '',
    decimals: 18,
    nativeGasToken: 'ETH',
    enabled: true,
    isNative: true,
    rateToUSD: 2850.0,
    icon: 'Ξ',
    color: '#8B5CF6',
    description: 'Native Ether on Ethereum L1',
  },
  {
    id: 'WBTC-1',
    symbol: 'WBTC',
    name: 'Wrapped Bitcoin (Ethereum)',
    network: 'Ethereum',
    chainId: 1,
    contractAddress: '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599',
    decimals: 8,
    nativeGasToken: 'ETH',
    enabled: true,
    rateToUSD: 96450.0,
    icon: '₿',
    color: '#F7931A',
    description: 'BitGo Wrapped BTC on Ethereum',
  },
  {
    id: 'VERSE-1',
    symbol: 'VERSE',
    name: 'Verse (Ethereum)',
    network: 'Ethereum',
    chainId: 1,
    contractAddress: import.meta.env.VITE_VERSE_TOKEN_ETHEREUM || '0x249ca82617ec3dfb2589c4c17ab7ec9765350a18',
    decimals: 18,
    nativeGasToken: 'ETH',
    enabled: true,
    rateToUSD: 0.0000176,
    icon: '⚡',
    color: '#00D2FE',
    description: 'Bitcoin.com Verse Token on Ethereum Mainnet',
  },
  {
    id: 'DAI-1',
    symbol: 'DAI',
    name: 'Dai Stablecoin (Ethereum)',
    network: 'Ethereum',
    chainId: 1,
    contractAddress: '0x6B175474E89094C44Da98b954EedeAC495271d0F',
    decimals: 18,
    nativeGasToken: 'ETH',
    enabled: true,
    rateToUSD: 1.0,
    icon: '◈',
    color: '#F59E0B',
    description: 'MakerDAO Dai ERC-20',
  },

  // 3. BASE MAINNET (Chain ID: 8453)
  {
    id: 'USDC-8453',
    symbol: 'USDC',
    name: 'USD Coin (Base)',
    network: 'Base',
    chainId: 8453,
    contractAddress: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
    decimals: 6,
    nativeGasToken: 'ETH',
    enabled: true,
    rateToUSD: 1.0,
    icon: '$',
    color: '#3B82F6',
    description: 'Circle Native USDC on Base L2',
  },
  {
    id: 'USDT-8453',
    symbol: 'USDT',
    name: 'Tether USD (Base)',
    network: 'Base',
    chainId: 8453,
    contractAddress: '0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2',
    decimals: 6,
    nativeGasToken: 'ETH',
    enabled: true,
    rateToUSD: 1.0,
    icon: '₮',
    color: '#10B981',
    description: 'Tether USD on Base L2',
  },
  {
    id: 'ETH-8453',
    symbol: 'ETH',
    name: 'Ethereum (Base)',
    network: 'Base',
    chainId: 8453,
    contractAddress: '',
    decimals: 18,
    nativeGasToken: 'ETH',
    enabled: true,
    isNative: true,
    rateToUSD: 2850.0,
    icon: 'Ξ',
    color: '#8B5CF6',
    description: 'Native Ether on Base L2',
  },
  {
    id: 'WBTC-8453',
    symbol: 'WBTC',
    name: 'Coinbase BTC (Base)',
    network: 'Base',
    chainId: 8453,
    contractAddress: '0x0555E30da8f98308EdB960aa94C0Db47230d2B9c',
    decimals: 8,
    nativeGasToken: 'ETH',
    enabled: true,
    rateToUSD: 96450.0,
    icon: '₿',
    color: '#F7931A',
    description: 'cbBTC / WBTC on Base',
  },

  // 4. ARBITRUM ONE (Chain ID: 42161)
  {
    id: 'USDC-42161',
    symbol: 'USDC',
    name: 'USD Coin (Arbitrum)',
    network: 'Arbitrum',
    chainId: 42161,
    contractAddress: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831',
    decimals: 6,
    nativeGasToken: 'ETH',
    enabled: true,
    rateToUSD: 1.0,
    icon: '$',
    color: '#3B82F6',
    description: 'Circle Native USDC on Arbitrum One',
  },
  {
    id: 'USDT-42161',
    symbol: 'USDT',
    name: 'Tether USD (Arbitrum)',
    network: 'Arbitrum',
    chainId: 42161,
    contractAddress: '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9',
    decimals: 6,
    nativeGasToken: 'ETH',
    enabled: true,
    rateToUSD: 1.0,
    icon: '₮',
    color: '#10B981',
    description: 'Tether USD on Arbitrum One',
  },
  {
    id: 'ETH-42161',
    symbol: 'ETH',
    name: 'Ethereum (Arbitrum)',
    network: 'Arbitrum',
    chainId: 42161,
    contractAddress: '',
    decimals: 18,
    nativeGasToken: 'ETH',
    enabled: true,
    isNative: true,
    rateToUSD: 2850.0,
    icon: 'Ξ',
    color: '#8B5CF6',
    description: 'Native Ether on Arbitrum One',
  },
  {
    id: 'WBTC-42161',
    symbol: 'WBTC',
    name: 'Wrapped Bitcoin (Arbitrum)',
    network: 'Arbitrum',
    chainId: 42161,
    contractAddress: '0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f',
    decimals: 8,
    nativeGasToken: 'ETH',
    enabled: true,
    rateToUSD: 96450.0,
    icon: '₿',
    color: '#F7931A',
    description: 'Wrapped BTC on Arbitrum One',
  },

  // 5. BNB SMART CHAIN (Chain ID: 56)
  {
    id: 'BNB-56',
    symbol: 'BNB',
    name: 'BNB (Native)',
    network: 'BNB Chain',
    chainId: 56,
    contractAddress: '',
    decimals: 18,
    nativeGasToken: 'BNB',
    enabled: true,
    isNative: true,
    rateToUSD: 645.0,
    icon: '🟡',
    color: '#F0B90B',
    description: 'Native BNB on BNB Smart Chain',
  },
  {
    id: 'USDT-56',
    symbol: 'USDT',
    name: 'Tether USD (BSC)',
    network: 'BNB Chain',
    chainId: 56,
    contractAddress: '0x55d398326f99059fF775485246999027B3197955',
    decimals: 18,
    nativeGasToken: 'BNB',
    enabled: true,
    rateToUSD: 1.0,
    icon: '₮',
    color: '#10B981',
    description: 'Binance-Peg Tether USD',
  },
  {
    id: 'USDC-56',
    symbol: 'USDC',
    name: 'USD Coin (BSC)',
    network: 'BNB Chain',
    chainId: 56,
    contractAddress: '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d',
    decimals: 18,
    nativeGasToken: 'BNB',
    enabled: true,
    rateToUSD: 1.0,
    icon: '$',
    color: '#3B82F6',
    description: 'Binance-Peg USD Coin',
  },
  {
    id: 'WBTC-56',
    symbol: 'WBTC',
    name: 'Bitcoin BEP-20 (BSC)',
    network: 'BNB Chain',
    chainId: 56,
    contractAddress: '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c',
    decimals: 18,
    nativeGasToken: 'BNB',
    enabled: true,
    rateToUSD: 96450.0,
    icon: '₿',
    color: '#F7931A',
    description: 'Binance-Peg BTCB Token',
  },

  // 6. AVALANCHE C-CHAIN (Chain ID: 43114)
  {
    id: 'AVAX-43114',
    symbol: 'AVAX',
    name: 'Avalanche (Native)',
    network: 'Avalanche',
    chainId: 43114,
    contractAddress: '',
    decimals: 18,
    nativeGasToken: 'AVAX',
    enabled: true,
    isNative: true,
    rateToUSD: 27.5,
    icon: '🔺',
    color: '#E84142',
    description: 'Native AVAX on Avalanche C-Chain',
  },
  {
    id: 'USDC-43114',
    symbol: 'USDC',
    name: 'USD Coin (Avalanche)',
    network: 'Avalanche',
    chainId: 43114,
    contractAddress: '0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E',
    decimals: 6,
    nativeGasToken: 'AVAX',
    enabled: true,
    rateToUSD: 1.0,
    icon: '$',
    color: '#3B82F6',
    description: 'Circle Native USDC on Avalanche',
  },
  {
    id: 'USDT-43114',
    symbol: 'USDT',
    name: 'Tether USD (Avalanche)',
    network: 'Avalanche',
    chainId: 43114,
    contractAddress: '0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7',
    decimals: 6,
    nativeGasToken: 'AVAX',
    enabled: true,
    rateToUSD: 1.0,
    icon: '₮',
    color: '#10B981',
    description: 'Tether USD on Avalanche C-Chain',
  },

  // 7. BITCOIN & SOLANA
  {
    id: 'BTC-L1',
    symbol: 'BTC',
    name: 'Bitcoin (Native Layer 1)',
    network: 'Bitcoin',
    chainId: 0,
    contractAddress: '',
    decimals: 8,
    nativeGasToken: 'BTC',
    enabled: true,
    isNative: true,
    rateToUSD: 96450.0,
    icon: '₿',
    color: '#F7931A',
    description: 'Native Bitcoin L1 Blockchain Settlement',
  },
  {
    id: 'SOL-L1',
    symbol: 'SOL',
    name: 'Solana (Solana Mainnet)',
    network: 'Solana Mainnet',
    chainId: 0,
    contractAddress: '',
    decimals: 9,
    nativeGasToken: 'SOL',
    enabled: true,
    isNative: true,
    rateToUSD: 184.2,
    icon: '🟣',
    color: '#14F195',
    description: 'Native Solana Mainnet High-Speed Settlement',
  },
];

export const getSupportedAsset = (symbol: SupportedToken, chainId: number): SupportedAsset | undefined => {
  return SUPPORTED_ASSETS.find((a) => a.symbol === symbol && a.chainId === chainId);
};

export const getAssetsByChain = (chainId: number): SupportedAsset[] => {
  return SUPPORTED_ASSETS.filter((a) => a.chainId === chainId && a.enabled);
};

export const getAssetsForChain = getAssetsByChain;

export function formatAssetLabel(assetOrSymbol: SupportedAsset | SupportedToken, chainId?: number): string {
  if (typeof assetOrSymbol === 'object' && assetOrSymbol !== null) {
    const chain = getChainConfig(assetOrSymbol.chainId);
    return `${assetOrSymbol.name} (${chain?.shortName || assetOrSymbol.network || 'Mainnet'})`;
  }
  const asset = chainId ? getSupportedAsset(assetOrSymbol as SupportedToken, chainId) : undefined;
  const chain = chainId ? getChainConfig(chainId) : undefined;
  return asset ? `${asset.name} (${chain?.shortName || 'Mainnet'})` : String(assetOrSymbol);
}

export const getAssetsBySymbol = (symbol: SupportedToken): SupportedAsset[] => {
  return SUPPORTED_ASSETS.filter((a) => a.symbol === symbol && a.enabled);
};
